name: Bug Report
description: Submit a bug report using this form.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please complete all the required fields below.
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Select the severity level of the issue.
      options:
        - PLACEHOLDER
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed explanation of the issue.
      placeholder: Describe the bug in detail...
